export const initialTravelPlan = {
    id: 0,
    title: '(根節點)',
    childPlaces: [{
      id: 1,
      title: '地球',
      childPlaces: [{
        id: 2,
        title: '非洲',
        childPlaces: [{
          id: 3,
          title: '波札那',
          childPlaces: []
        }, {
          id: 4,
          title: '埃及',
          childPlaces: []
        }, {
          id: 5,
          title: '肯亞',
          childPlaces: []
        }, {
          id: 6,
          title: '馬達加斯加',
          childPlaces: []
        }, {
          id: 7,
          title: '摩洛哥',
          childPlaces: []
        }, {
          id: 8,
          title: '奈及利亞',
          childPlaces: []
        }, {
          id: 9,
          title: '南非',
          childPlaces: []
        }]
      }, {
        id: 10,
        title: '美洲',
        childPlaces: [{
          id: 11,
          title: '阿根廷',
          childPlaces: []
        }, {
          id: 12,
          title: '巴西',
          childPlaces: []
        }, {
          id: 13,
          title: '巴貝多',
          childPlaces: []
        }, {
          id: 14,
          title: '加拿大',
          childPlaces: []
        }, {
          id: 15,
          title: '牙買加',
          childPlaces: []
        }, {
          id: 16,
          title: '墨西哥',
          childPlaces: []
        }, {
          id: 17,
          title: '千里達及托巴哥',
          childPlaces: []
        }, {
          id: 18,
          title: '委內瑞拉',
          childPlaces: []
        }]
      }, {
        id: 19,
        title: '亞洲',
        childPlaces: [{
          id: 20,
          title: '中國',
          childPlaces: []
        }, {
          id: 21,
          title: '印度',
          childPlaces: []
        }, {
          id: 22,
          title: '新加坡',
          childPlaces: []
        }, {
          id: 23,
          title: '南韓',
          childPlaces: []
        }, {
          id: 24,
          title: '泰國',
          childPlaces: []
        }, {
          id: 25,
          title: '越南',
          childPlaces: []
        }]
      }, {
        id: 26,
        title: '歐洲',
        childPlaces: [{
          id: 27,
          title: '克羅埃西亞',
          childPlaces: [],
        }, {
          id: 28,
          title: '法國',
          childPlaces: [],
        }, {
          id: 29,
          title: '德國',
          childPlaces: [],
        }, {
          id: 30,
          title: '義大利',
          childPlaces: [],
        }, {
          id: 31,
          title: '葡萄牙',
          childPlaces: [],
        }, {
          id: 32,
          title: '西班牙',
          childPlaces: [],
        }, {
          id: 33,
          title: '土耳其',
          childPlaces: [],
        }]
      }, {
        id: 34,
        title: '大洋洲',
        childPlaces: [{
          id: 35,
          title: '澳洲',
          childPlaces: [],
        }, {
          id: 36,
          title: '波拉波拉島（法屬玻里尼西亞）',
          childPlaces: [],
        }, {
          id: 37,
          title: '復活節島（智利）',
          childPlaces: [],
        }, {
          id: 38,
          title: '斐濟',
          childPlaces: [],
        }, {
          id: 39,
          title: '夏威夷（美國）',
          childPlaces: [],
        }, {
          id: 40,
          title: '紐西蘭',
          childPlaces: [],
        }, {
          id: 41,
          title: '萬那杜',
          childPlaces: [],
        }]
      }]
    }, {
      id: 42,
      title: '月球',
      childPlaces: [{
        id: 43,
        title: '雷塔環形山',
        childPlaces: []
      }, {
        id: 44,
        title: '皮科洛米尼環形山',
        childPlaces: []
      }, {
        id: 45,
        title: '第谷環形山',
        childPlaces: []
      }]
    }, {
      id: 46,
      title: '火星',
      childPlaces: [{
        id: 47,
        title: '玉米鎮',
        childPlaces: []
      }, {
        id: 48,
        title: '綠山', 
        childPlaces: []      
      }]
    }]
  };
  